data:
  dataset_root: "/exchange/dspro01/HSLU.DSPRO1.BirdDetection/data/processed/bird-whisperer-denoised/"
  batch_size: 24
  num_workers: 4
  train_parquet_name: "train_cutoff.parquet"
  test_parquet_name: "test_cutoff.parquet"
  with_augmented: false

model:
  model_dir: "../../data/bird-whisperer/models/"
  checkpoint_path: "../../data/bird-whisperer/models/trained/best_model.pt"
