data:
  dataset_root: "../../data/processed/bird-whisperer/"
  batch_size: 24
  num_workers: 4
  train_parquet_name: "train.parquet"
  test_parquet_name: "test.parquet"
  with_augmented: false

model:
  model_dir: "../../data/bird-whisperer/models/"
  checkpoint_path: "../../data/bird-whisperer/models/trained/best_model.pt"
