audio:
  sample_rate: 16000
  segment_duration: 30
  target_db_level: -20

data:
  train_data_path: "../../data/processed/bird-whisperer/train.parquet"
  test_data_path: "../../data/processed/bird-whisperer/test.parquet"
  evaluation_data_path: "../../data/processed/bird-whisperer/test.parquet"

model:
  model_dir: "../../data/bird-whisperer/models/"
  checkpoint_path: "../../data/bird-whisperer/models/trained/best_model.pth"
